In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../../data/epl_matches.csv')
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,pk,fk,pkatt,dist,name,season
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,...,Match Report,NaN,18.0,4.0,0,1.0,0,17.3,Manchester City,2022
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,...,Match Report,NaN,16.0,4.0,0,1.0,0,18.5,Manchester City,2022
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,...,Match Report,NaN,25.0,10.0,0,0.0,0,14.8,Manchester City,2022
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,...,Match Report,NaN,25.0,8.0,0,0.0,0,14.3,Manchester City,2022
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,...,Match Report,NaN,16.0,1.0,0,1.0,0,16.4,Manchester City,2022

In [3]:
# Rename column name to team
df.rename(columns= { 'name': 'team' }, inplace= True)

In [4]:
# Remove trailing spaces from the team name
df['team'] = df['team'].str.strip()

In [5]:
df[df['team'] == 'Liverpool']

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,pk,fk,pkatt,dist,team,season
38,0,2021-08-14,17:30,Premier League,Matchweek 1,Sat,Away,W,3,0,...,Match Report,NaN,19.0,6.0,0,1.0,0,17.3,Liverpool,2022
39,1,2021-08-21,12:30,Premier League,Matchweek 2,Sat,Home,W,2,0,...,Match Report,NaN,27.0,8.0,0,0.0,0,16.1,Liverpool,2022
40,2,2021-08-28,17:30,Premier League,Matchweek 3,Sat,Home,D,1,1,...,Match Report,NaN,23.0,6.0,1,0.0,1,16.2,Liverpool,2022
41,3,2021-09-12,16:30,Premier League,Matchweek 4,Sun,Away,W,3,0,...,Match Report,NaN,30.0,8.0,0,1.0,0,16.1,Liverpool,2022
42,5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,W,3,0,...,Match Report,NaN,25.0,10.0,0,1.0,0,16.4,Liverpool,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2,0,...,Match Report,NaN,14.0,6.0,0,0.0,0,13.6,Liverpool,2021
870,49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4,2,...,Match Report,NaN,17.0,8.0,0,0.0,0,14.9,Liverpool,2021
871,50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2,1,...,Match Report,NaN,26.0,6.0,0,1.0,0,18.3,Liverpool,2021
872,51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3,0,...,Match Report,NaN,20.0,3.0,0,1.0,0,16.2,Liverpool,2021
873,52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2,0,...,Match Report,NaN,19.0,5.0,0,1.0,0,14.7,Liverpool,2021

In [6]:
df['round'].value_counts()

round
Matchweek 1     40
Matchweek 29    40
Matchweek 22    40
Matchweek 23    40
Matchweek 24    40
Matchweek 25    40
Matchweek 26    40
Matchweek 27    40
Matchweek 28    40
Matchweek 31    40
Matchweek 2     40
Matchweek 32    40
Matchweek 30    40
Matchweek 34    40
Matchweek 35    40
Matchweek 36    40
Matchweek 33    40
Matchweek 37    40
Matchweek 21    40
Matchweek 20    40
Matchweek 19    40
Matchweek 18    40
Matchweek 3     40
Matchweek 4     40
Matchweek 5     40
Matchweek 6     40
Matchweek 7     40
Matchweek 8     40
Matchweek 9     40
Matchweek 10    40
Matchweek 11    40
Matchweek 12    40
Matchweek 13    40
Matchweek 14    40
Matchweek 15    40
Matchweek 16    40
Matchweek 17    40
Matchweek 38    40
Name: count, dtype: int64

In [7]:
# Convert date from string to pd.datetime
df['date'] = pd.to_datetime(df['date'])

In [8]:
df.dtypes

Unnamed: 0                int64
date             datetime64[ns]
time                     object
comp                     object
round                    object
day                      object
venue                    object
result                   object
gf                        int64
ga                        int64
opponent                 object
xg                      float64
xga                     float64
poss                    float64
attendance              float64
captain                  object
formation                object
opp formation            object
referee                  object
match report             object
notes                   float64
sh                      float64
sot                     float64
pk                        int64
fk                      float64
pkatt                     int64
dist                    float64
team                     object
season                    int64
dtype: object

In [9]:
# Create a simple predictor
df['venue_code'] = df['venue'].astype('category').cat.codes

In [10]:
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,notes,sh,sot,pk,fk,pkatt,dist,team,season,venue_code
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,...,NaN,18.0,4.0,0,1.0,0,17.3,Manchester City,2022,0
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,...,NaN,16.0,4.0,0,1.0,0,18.5,Manchester City,2022,1
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,...,NaN,25.0,10.0,0,0.0,0,14.8,Manchester City,2022,1
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,...,NaN,25.0,8.0,0,0.0,0,14.3,Manchester City,2022,0
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,...,NaN,16.0,1.0,0,1.0,0,16.4,Manchester City,2022,1

In [11]:
df['opp_code'] = df['opponent'].astype('category').cat.codes
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,sh,sot,pk,fk,pkatt,dist,team,season,venue_code,opp_code
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,...,18.0,4.0,0,1.0,0,17.3,Manchester City,2022,0,18
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,...,16.0,4.0,0,1.0,0,18.5,Manchester City,2022,1,15
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,...,25.0,10.0,0,0.0,0,14.8,Manchester City,2022,1,0
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,...,25.0,8.0,0,0.0,0,14.3,Manchester City,2022,0,10
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,...,16.0,1.0,0,1.0,0,16.4,Manchester City,2022,1,17

In [12]:
df['hour'] = df['time'].replace(':.+', '', regex= True).astype('int')
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,sot,pk,fk,pkatt,dist,team,season,venue_code,opp_code,hour
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,...,4.0,0,1.0,0,17.3,Manchester City,2022,0,18,16
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,...,4.0,0,1.0,0,18.5,Manchester City,2022,1,15,15
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,...,10.0,0,0.0,0,14.8,Manchester City,2022,1,0,12
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,...,8.0,0,0.0,0,14.3,Manchester City,2022,0,10,15
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,...,1.0,0,1.0,0,16.4,Manchester City,2022,1,17,15

In [13]:
df['day_code'] = df['date'].dt.day_of_week
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,pk,fk,pkatt,dist,team,season,venue_code,opp_code,hour,day_code
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,...,0,1.0,0,17.3,Manchester City,2022,0,18,16,6
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,...,0,1.0,0,18.5,Manchester City,2022,1,15,15,5
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,...,0,0.0,0,14.8,Manchester City,2022,1,0,12,5
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,...,0,0.0,0,14.3,Manchester City,2022,0,10,15,5
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,...,0,1.0,0,16.4,Manchester City,2022,1,17,15,5

In [14]:
df['target'] = (df['result'] == 'W').astype('int')
df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,fk,pkatt,dist,team,season,venue_code,opp_code,hour,day_code,target
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,...,1.0,0,17.3,Manchester City,2022,0,18,16,6,0
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,...,1.0,0,18.5,Manchester City,2022,1,15,15,5,1
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,...,0.0,0,14.8,Manchester City,2022,1,0,12,5,1
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,...,0.0,0,14.3,Manchester City,2022,0,10,15,5,1
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,...,1.0,0,16.4,Manchester City,2022,1,17,15,5,0

In [15]:
df['result'].astype('category').cat.codes

0       1
1       2
2       2
3       2
4       0
       ..
1515    1
1516    1
1517    2
1518    1
1519    2
Length: 1520, dtype: int8

In [16]:
# Creating the machine learning model
from sklearn.ensemble import RandomForestClassifier

In [17]:
rf = RandomForestClassifier(n_estimators= 50, min_samples_split= 10)

In [18]:
train = df[df['date'] < '2022-01-01']

In [19]:
test = df[df['date'] >= '2022-01-01']

In [20]:
predictors = ['venue_code', 'opp_code', 'hour', 'day_code']

In [21]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50)

In [22]:
prediction = rf.predict(test[predictors])

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
acc = accuracy_score(test['target'], prediction)

In [25]:
acc

0.5964467005076142

In [26]:
combined = pd.DataFrame(dict(actual= test['target'], prediction= prediction))

In [27]:
pd.crosstab(index=combined['actual'], columns= combined['prediction'])

prediction    0   1
actual
0           187  49
1           110  48

In [28]:
from sklearn.metrics import precision_score

In [29]:
precision_score(test['target'], prediction)

0.4948453608247423

In [30]:
grouped_matches = df.groupby('team')

In [31]:
group = grouped_matches.get_group('Manchester City')

In [32]:
#group

In [33]:
# What was the performance (average) in the n previous matches 

def rolling_averages(group, cols, new_cols):
    group = group.sort_values('date')

    # Include only the past 3 days data
    rolling_stats = group[cols].rolling(3, closed= 'left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset= new_cols)
    return group

In [34]:
cols = ['gf', 'ga', 'sh', 'sot', 'dist', 'fk', 'pk', 'pkatt']
new_cols = [f'{c}_rolling' for c in cols]

In [35]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [36]:
rolling_averages(group, cols, new_cols)

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
763,5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1,0,...,5,1,2.000000,2.333333,17.333333,4.666667,19.700000,1.333333,0.333333,0.333333
764,7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1,1,...,5,0,1.333333,2.000000,17.333333,3.666667,18.566667,0.666667,0.000000,0.000000
765,9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1,0,...,5,1,1.000000,0.666667,16.666667,4.333333,18.933333,0.666667,0.000000,0.000000
766,11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1,1,...,6,0,1.000000,0.333333,14.333333,6.666667,19.033333,1.000000,0.000000,0.000000
767,12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0,2,...,5,0,1.000000,0.666667,12.000000,5.666667,20.000000,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4,0,...,5,1,3.333333,1.000000,16.000000,5.333333,17.466667,0.333333,0.333333,0.333333
34,54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5,0,...,6,1,4.000000,0.333333,18.666667,6.000000,16.933333,0.000000,0.333333,0.333333
35,55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5,1,...,2,1,4.666667,0.333333,20.000000,7.333333,15.600000,0.333333,0.333333,0.333333
36,56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2,2,...,6,0,4.666667,0.333333,18.333333,6.666667,15.633333,0.333333,0.000000,0.000000
37,57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,2,...,6,1,4.000000,1.000000,22.000000,7.000000,16.433333,1.000000,0.000000,0.333333

In [37]:
matches_rolling = df.groupby('team', as_index= False).apply(lambda x: rolling_averages(x, cols, new_cols))

/var/folders/bj/t8_jdq_92dvc7m96_2p7qkym0000gn/T/ipykernel_80776/757549309.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = df.groupby('team', as_index= False).apply(lambda x: rolling_averages(x, cols, new_cols))

In [38]:
matches_rolling.index = matches_rolling.index.droplevel(0)

In [39]:
matches_rolling.index = range(matches_rolling.shape[0])

In [40]:
matches_rolling

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,37,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Home,L,0,3,...,5,0,0.666667,1.000000,8.666667,3.333333,17.400000,0.000000,0.000000,0.000000
1444,38,2022-05-07,15:00,Premier League,Matchweek 36,Sat,Away,D,2,2,...,5,0,0.000000,1.666667,8.666667,2.333333,18.633333,0.333333,0.000000,0.000000
1445,39,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Home,L,1,5,...,2,0,0.666667,2.000000,11.666667,3.000000,17.766667,0.333333,0.000000,0.000000
1446,40,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,...,6,0,1.000000,3.333333,10.666667,2.666667,17.066667,0.333333,0.000000,0.000000
1447,41,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Away,L,1,3,...,6,0,1.333333,2.666667,12.666667,3.666667,17.766667,0.333333,0.000000,0.000000

In [41]:
# Retraining the model
def make_predictions(data, predictors):
    train = data[data['date'] < '2022-01-01']
    test = data[data['date'] >= '2022-01-01']

    rf.fit(train[predictors], train['target'])
    prediction = rf.predict(test[predictors])

    combined = pd.DataFrame(dict(actual= test['target'], prediction= prediction))
    combined = combined.merge(data[['date', 'team', 'opponent', 'result']], left_index= True, right_index= True)
    pd.crosstab(index=combined['actual'], columns= combined['prediction'])
    precision = precision_score(test['target'], prediction)

    return combined, precision

In [42]:
combined, precision = make_predictions(matches_rolling, predictors+new_cols)

In [43]:
precision

0.5876288659793815

In [44]:
combined

,actual,prediction,date,team,opponent,result
54,0,0,2022-01-01,Arsenal,Manchester City,L
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,1,2022-02-10,Arsenal,Wolves,W
57,1,1,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
...,...,...,...,...,...,...
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L

In [45]:
class MissingDict(dict):
    __missing__ = lambda self, key: key


map_values = {
    'Brighton and Hove Albion': 'Brighton',
    'Manchester United': 'Manchester Utd',
    'Newcastle United': 'Newcastle Utd',
    'Tottenham Hotspur': 'Tottenham',
    'West Ham United': 'West Ham',
    'Wolverhampton Wanderers': 'Wolves'
}

mapping = MissingDict(**map_values)

In [46]:
combined['new_team'] = combined['team'].map(mapping)

In [47]:
combined.tail()

,actual,prediction,date,team,opponent,result,new_team
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolves
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves

In [48]:
merged = combined.merge(combined, left_on= ['date', 'new_team'], right_on= ['date', 'opponent'])

In [49]:
merged

,actual_x,prediction_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,prediction_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-01,Arsenal,Manchester City,L,Arsenal,1,1,Manchester City,Arsenal,W,Manchester City
1,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
2,1,1,2022-02-10,Arsenal,Wolves,W,Arsenal,0,1,Wolverhampton Wanderers,Arsenal,L,Wolves
3,1,1,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
4,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolves,1,0,Brighton and Hove Albion,Wolves,W,Brighton
390,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves,0,0,Chelsea,Wolves,D,Chelsea
391,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City
392,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves,0,0,Norwich City,Wolves,D,Norwich City
393,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,1,Liverpool,Wolves,W,Liverpool

In [50]:
merged[(merged['prediction_x'] == 1) & (merged['prediction_y'] == 0)]['actual_x'].value_counts()

actual_x
1    50
0    33
Name: count, dtype: int64

In [51]:
44/(44 + 38)

0.5365853658536586

To extend
- Scrape more data
- Use more of the columns to generate prediction
- Try a different algorithm
- Integrate more additional data from different leagues
- Check current team and opponent records